#!/bin/sh
#
# Run all dotfiles installers.
set -e

# Run Homebrew through the Brewfile
echo "› brew bundle"

cd homebrew
brew bundle

cd "$(dirname "$0")"/..

# find the installers and run them iteratively
git ls-tree --name-only -r HEAD | grep install.sh | while read -r installer; do
	echo "› ${installer}..."
	sh -c "$installer"
done
